[[commands]]
name = "cdktf"
package = "nodePackages_latest.cdktf-cli"

[[commands]]
package = "go"

[[commands]]
package = "gotest"

[[commands]]
name = "make"
package = "gnumake"

[[commands]]
name = "oci"
package = "oci-cli"

[[commands]]
package = "terraform"

[devshell]
packages = [
  "nodejs_22",
]
