name: Go-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Nix Build
        run: nix build

      - name: Nix Flake
        run: nix flake check

      - name: devshell
        run: nix develop

      - name: Test with the Go CLI
        run: make
